### ISSUE TITLE
Allow the user to state which files to include

### ISSUE THREAD

**Issue by bitstein** [khromov/ai-digest#7]
Right now, the program assumes everything should be included, ignoring only what is in the ignore file.

It would be nice to be able to whitelist files instead. This would allow me to create lists of files pertaining to particular sets of files in my code related to one another. That way, I could feed only the files I care about at the moment to an LLM to save on tokens.

**Comment by khromov** [comment]
👋 Thanks for the feedback. Unfortunately I don't think this will be added because the philosophy of this tool is to include most of your project, not specific files.

If you search online or check out the /r/claudeai subreddit there are several other alternatives written in different programming languages that does the same type of file merging, perhaps some of these tools have this feature.

**Comment by bitstein** [comment]
Understood, thanks!
